### ISSUE TITLE
Old registry / plone.app.collection 

### ISSUE THREAD

**Issue by bsuttor** [IMIO/cpskin.core#1]
Some registry are still present un portal_regisrty, but no more use :
- IAmTags
- HiddenTags
- ISearchTags

I'm talking about registry used by plone.app.collection. We should remove them.
Currently, I just disabled them on ath.

![screenshot from 2014-08-07 08 19 39](https://cloud.githubusercontent.com/assets/646703/3837983/efa4437a-1dfa-11e4-886b-97481b1d98c9.png)

**Comment by laulaz** [comment]
Je ferme cette issue. A réouvrir si nécessaire.
